### ISSUE TITLE
Moving tasks between columns got broken

### ISSUE THREAD

**Issue by visibilityspots** [TehShrike/k#7]
```
$ k move left
ERROR cannot POST /index.php/api/kanbanize/move_task/boardid/33/format/json (400)
```

**Comment by visibilityspots** [comment]
After updating to version 1.4.1 this issue was resolved.

closed by https://github.com/TehShrike/k/commit/719b3f74fdfbadf0e0bde0c2678cbcbbb0dfda54

**Comment by TehShrike** [comment]
Weird, this is still happening to me and I can't figure out why.  The API request looks reasonable to me.  I've emailed Kanbanize's support.
